[workspace]
pr_branch_prefix = "release-plz-"
# Only publish when the release PR is merged
# https://release-plz.dev/docs/config#the-release_always-field
release_always = false
# Skip GitHub releases and git tags by default, individual crates can opt in.
# We don't want release-plz creating tags for every published crate.
git_release_enable = false
git_tag_enable = false
# set the path of all the crates to the changelog to the root of the repository
changelog_path = "./CHANGELOG.md"

[[package]]
# The version bumps from any compiler crate should bubble up and bump the
# `cargo-miden` version. Plus, any change to `cargo-miden` alone also calls for
# the compiler release.
name = "cargo-miden"
git_release_enable = true
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"


[changelog]
# group all the changes from all the packages in a single changelog
# via https://release-plz.dev/docs/extra/single-changelog
body = """

## `{{ package }}` - [{{ version }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
{%- if commit.scope -%}
- *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{% endif -%}
{% endfor -%}
{% endfor -%}
"""
