[workspace]
pr_branch_prefix = "release-plz-"
# Only publish when the release PR is merged
# https://release-plz.dev/docs/config#the-release_always-field
release_always = false
# Skip GitHub releases and git tags by default, individual crates can opt in
git_release_enable = false
git_tag_enable = false

[[package]]
name = "midenc"
git_release_enable = true
git_tag_enable = true
git_tag_name = "{{ version }}"
git_release_name = "{{ version }}"

# SDK
[[package]]
name = "miden"
git_release_enable = false
git_tag_enable = true
git_tag_name = "SDK-v{{ version }}"
