[package]
name = "miden-test-harness-lib"
description = "Custom testing harness used in rust code targetting the miden compiler."
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]
libtest-mimic = "0.8.1"
miden-objects = "0.12.4"
miden-mast-package.workspace = true
inventory.workspace = true
clap.workspace = true
miden-testing = "0.12.4"
