[package]
name = "miden-test-harness"
description = "Custom testing harness used in rust code targetting the miden compiler."
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
path = "src/mod.rs"

[dependencies]
libtest-mimic = "0.8.1"
inventory.workspace = true
clap.workspace = true

# Miden dependencies
miden-test-harness-macros.workspace = true
miden-testing = "0.12.4"
miden-objects = "0.12.4"
