[package]
name = "miden-base-sys"
description = "Miden rollup Rust bingings and MASM library"
version = "0.8.1"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
build = "build.rs"
links = "miden_base_sys_stubs"

[dependencies]
miden-stdlib-sys = { version = "0.8.0", path = "../stdlib-sys" }
miden-field-repr = { version = "0.7.1", path = "../field-repr/repr" }

[features]
default = []
