[package]
name = "cargo-miden"
description = "A cargo extension to build Miden projects"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
autotests = false                                         # disable autodiscovery of tests

[[bin]]
name = "cargo-miden"

[[test]]
name = "integration"
path = "tests/mod.rs"

[dependencies]
midenc-compile.workspace = true
midenc-session.workspace = true
env_logger.workspace = true
log.workspace = true
clap.workspace = true
anyhow.workspace = true
cargo-component = { version = "0.21" }
cargo-component-core = { version = "0.21" }
cargo_metadata = "0.19"
cargo-generate = "0.23"
path-absolutize = "3.1.1"
tokio.workspace = true
cargo-config2 = "0.1.24"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
serde_json = "1.0"                                 # Added serde_json

[dev-dependencies]
miden-mast-package.workspace = true
