[package]
name = "cargo-miden"
description = "A cargo extension to build Miden projects"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true
autotests = false                                         # disable autodiscovery of tests

[[bin]]
name = "cargo-miden"

[[test]]
name = "integration"
path = "tests/mod.rs"

[dependencies]
midenc-compile.workspace = true
midenc-session.workspace = true
env_logger.workspace = true
log.workspace = true
clap.workspace = true
anyhow.workspace = true
cargo-component = { version = "0.20.0-dev", git = "https://github.com/greenhat/cargo-component", rev = "093ee4ce75e67814e9ec912faed87160e9a762ca" }
cargo-component-core = { version = "0.20.0-dev", git = "https://github.com/greenhat/cargo-component", rev = "093ee4ce75e67814e9ec912faed87160e9a762ca" }
cargo_metadata = "0.18"
cargo-generate = "0.22"
semver = "1.0.20"
parse_arg = "0.1.4"
path-absolutize = "3.1.1"
tokio.workspace = true
cargo-config2 = "0.1.24"

[dev-dependencies]
miden-mast-package.workspace = true
