[package]
name = "miden-field-repr"
description = "Serialization/deserialization for felt representation"
version = "0.10.0"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
miden-field-repr-derive = { path = "../derive", version = "0.10.0" }
miden-field.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
miden-core.workspace = true

[features]
default = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(miden)"] }
