[package]
name = "miden"
description = "Miden SDK"
version = "0.5.0"
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
miden-sdk-alloc = { version = "0.5.0", path = "../alloc" }
miden-stdlib-sys = { version = "0.5.0", path = "../stdlib-sys" }
miden-base = { version = "0.5.0", path = "../base" }
miden-base-sys = { version = "0.5.0", path = "../base-sys" }
wit-bindgen = { version = "0.46", default-features = false, features = ["macros"] }
wit-bindgen-rt = { version = "0.44", default-features = false, features = ["bitflags"] }

[features]
default = []
