[book]
authors      = ["Miden contributors"]
description  = "Manual for the Miden compiler"
language     = "en"
multilingual = false
title        = "The Miden Compiler Guide"

[output.html]
git-repository-url = "https://github.com/0xPolygonMiden/compiler"

[preprocessor.katex]
after = ["links"]

[preprocessor.alerts]

[output.linkcheck]
